bank3 = [
['orang','http://finalnotemagazine.com/wp-content/uploads/2018/09/thomas-guthrie-3.jpg','Thomas Guthrie'],
['orang','https://store.acsouth.com/assets/images/john-reed@2x.jpg','John Reed'],
['orang','https://upload.wikimedia.org/wikipedia/commons/3/37/Neith_Nevelson%2C_2004%2C_Miami.jpg','Neith Nevelson'],
['orang','https://www.pmi.com/resources/images/default-source/board-of-directors/harold-brown.jpg?sfvrsn=c52cb6b5_3&imwidth=1920&imdensity=1','Harold Brown'],
['orang','https://images.tapology.com/letterbox_images/242287/default/Jamal-Yusupov.png?1573495983','Jamal Yusupov'],
['orang','https://rslvwm.s3.amazonaws.com/I/images/132200/photo/profile_pic_4146345.JPG','Frederick Watson'],
['orang','https://i.cbc.ca/1.4097460.1520649309!/fileImage/httpImage/image.jpg_gen/derivatives/original_1180/robert-dennis.jpg','Robert Dennis'],
['orang','https://www.catholicregister.org/media/k2/items/cache/fbb4ded4081904a08327419b78b712e3_XL.jpg','Fr. Frank Portelli'],
['orang','http://cooksonscartoons.com/img/cook-smoke.gif','Bernard Cookson'],
['orang','https://www.crimescene.com/images/cache/c068c5628f3f366c82039158bda6a5a8_w180_h180%20crop.jpg','Warren Lee'],
['orang','https://previews.magnoliabox.com/printcollector/mb_hero/1630852/MUS-FAFP1114_black_850.jpg','Frank Lockwood'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Nick-Curran_2007.jpg/330px-Nick-Curran_2007.jpg','Nick Curran'],
['orang','https://upload.wikimedia.org/wikipedia/commons/2/2a/Cesare_Correnti_anziano.gif','Cesare Correnti'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ken-Marti_Vaher%2C_2011.jpg/330px-Ken-Marti_Vaher%2C_2011.jpg','Ken-Marti Vaher'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Jean-Louis-Costes-Dijon-2009-03.JPG/330px-Jean-Louis-Costes-Dijon-2009-03.JPG','Jean-Louis Costes'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Clio_Goldsmith_in_Miele_di_donna.jpg/330px-Clio_Goldsmith_in_Miele_di_donna.jpg','Clio Goldsmith'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Yekaterina_Sheremeteva.jpg/225px-Yekaterina_Sheremeteva.jpg','Countess Yekaterina Pavlovna Sheremeteva'],
['orang','https://upload.wikimedia.org/wikipedia/commons/5/53/Henry_Buchtel.gif','Henry Augustus Buchtel'],
['orang','https://www.archiwum.kalisz.pl/zdjecia/wystawyonline/008/015-m.jpg','Generał Mieczysław Smorawiński'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Kelly_Cooke.jpg/330px-Kelly_Cooke.jpg','Kelly Cooke'],
['orang','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Mike_Blaisdell.png/230px-Mike_Blaisdell.png','Mike Blaisdell'],
]